artifact_uri: file:///Users/federicovilla/github-unal/PRE-08-mlflow-tracking-local-fede386/my_mlruns/895294641979992189/e4fa4e66b62b4c9faf118965facb34cb/artifacts
end_time: 1748138308107
entry_point_name: ''
experiment_id: '895294641979992189'
lifecycle_stage: active
run_id: e4fa4e66b62b4c9faf118965facb34cb
run_name: elasticnet_33fdf4fc
run_uuid: e4fa4e66b62b4c9faf118965facb34cb
source_name: ''
source_type: 4
source_version: ''
start_time: 1748138308088
status: 3
tags: []
user_id: federicovilla
