artifact_location: file:///Users/federicovilla/github-unal/PRE-08-mlflow-tracking-local-fede386/my_mlruns/895294641979992189
creation_time: 1748138299778
experiment_id: '895294641979992189'
last_update_time: 1748138299778
lifecycle_stage: active
name: wine_quality_experiment
